name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

    - name: Install SDL2 on macOS
      if: matrix.os == 'macos-latest'
      run: brew install sdl2

    - name: Install vcpkg and SDL2 on Windows
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        bootstrap-vcpkg.bat
        vcpkg.exe integrate install
        vcpkg.exe install sdl2:x64-windows
        vcpkg.exe list

    - name: Configure CMake (Ubuntu/macOS)
      if: matrix.os != 'windows-latest'
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=%CD%\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build