name: CI

on: [push, pull_request]

jobs:
  # Job for Ubuntu
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libgl1-mesa-dev

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: ctest --test-dir build

  # Job for macOS
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: brew install sdl2

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: ctest --test-dir build
  
  # Job for Windows
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: vcpkg-cache-sdl2-${{ runner.os }}

      - name: Install vcpkg and SDL2
        shell: cmd
        run: |
          if not exist vcpkg (
            git clone https://github.com/microsoft/vcpkg.git
            cd vcpkg
            call bootstrap-vcpkg.bat
          ) else (
            cd vcpkg
          )
          vcpkg.exe install sdl2:x64-windows glew:x64-windows

      - name: Configure CMake
        shell: cmd
        run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: ctest --test-dir build -C Release --rerun-failed --output-on-failure